

CREATE TABLE IF NOT EXISTS `organizations` (
  `id` int(11) NOT NULL,
  `name` text,
  `email` text,
  `address` text,
  `paid` tinyint(1) DEFAULT NULL,
  `comment` text,
  `accountID` int(11) DEFAULT NULL,
  `reg_teams` int(11) DEFAULT '0',
  `reg_students` int(11) DEFAULT '0',
  `payment` varchar(10) NOT NULL DEFAULT '0',
  `canceled` tinyint(1) DEFAULT NULL,
  `paid2` tinyint(1) DEFAULT NULL,
  `proctors` text,
  `school_type` varchar(200) DEFAULT NULL,
  `division` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
);

INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(22, 'Beijing STFX Education', NULL, NULL, NULL, NULL, 25, 0, 0, '0', NULL, NULL, NULL, NULL, 7);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(25, 'Lehigh Valley', NULL, NULL, NULL, NULL, 28, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(26, 'Somerset High School', NULL, NULL, NULL, NULL, 29, 0, 0, '0', NULL, NULL, NULL, NULL, 7);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(27, 'Albany Area Math Circle', NULL, NULL, NULL, NULL, 30, 0, 0, '0', NULL, NULL, NULL, NULL, 7);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(29, 'Vestavia Hills High School', NULL, NULL, NULL, NULL, 32, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(30, 'Thomas Jefferson HS for Science and Technology', NULL, NULL, NULL, NULL, 33, 0, 0, '0', NULL, NULL, NULL, NULL, 7);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(31, 'Worcester Academy', NULL, NULL, NULL, NULL, 34, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(32, 'ABRHS', NULL, NULL, NULL, NULL, 35, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(35, 'Great Neck South High School', NULL, NULL, NULL, NULL, 38, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(36, 'Hopkins School', NULL, NULL, NULL, NULL, 39, 0, 0, '0', NULL, NULL, NULL, NULL, 7);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(37, 'Regis High School', NULL, NULL, NULL, NULL, 40, 0, 0, '0', NULL, NULL, NULL, NULL, 7);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(38, 'Illinois Mathematics and Science Academy', NULL, NULL, NULL, NULL, 41, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(39, 'The Hotchkiss School', NULL, NULL, NULL, NULL, 42, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(40, 'South Brunswick High School', NULL, NULL, NULL, NULL, 43, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(42, 'Emma Willard School', NULL, NULL, NULL, NULL, 45, 0, 0, '0', NULL, NULL, NULL, NULL, 7);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(43, 'The Roxbury Latin School', NULL, NULL, NULL, NULL, 46, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(44, 'Ward Melville Senior High School', NULL, NULL, NULL, NULL, 47, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(33, 'North Quincy High School', NULL, NULL, NULL, NULL, 36, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(46, 'West Windsor-Plainsboro High School North', NULL, NULL, NULL, NULL, 49, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(48, 'Sabio Academy', NULL, NULL, NULL, NULL, 51, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(51, 'Bishop Brady High School', NULL, NULL, NULL, NULL, 54, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(52, 'Oak Park and River Forest High School', NULL, NULL, NULL, NULL, 55, 0, 0, '0', NULL, NULL, NULL, NULL, 7);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(54, 'Loomis Chaffee School', NULL, NULL, NULL, NULL, 57, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(59, 'SH High School', NULL, NULL, NULL, NULL, 61, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(58, 'Phillips Exeter Academy', NULL, NULL, NULL, NULL, 60, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(61, 'Portsmouth Abbey School', NULL, NULL, NULL, NULL, 63, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(63, 'Nashoba Regional High School', NULL, NULL, NULL, NULL, 65, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(66, 'Lincoln-Sudbury Regional High School', NULL, NULL, NULL, NULL, 68, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(72, 'Detroit Country Day School', NULL, NULL, NULL, NULL, 74, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(73, 'Hunter College High School', NULL, NULL, NULL, NULL, 75, 0, 0, '0', NULL, NULL, NULL, NULL, 7);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(53, 'Westborough High School', NULL, NULL, NULL, NULL, 56, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(76, 'deerfield academy', NULL, NULL, NULL, NULL, 78, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(78, 'Hastings High School', NULL, NULL, NULL, NULL, 80, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(81, 'Malden Catholic High School', NULL, NULL, NULL, NULL, 83, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(85, 'Hoover High School', NULL, NULL, NULL, NULL, 87, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(87, 'New York City Math Team', NULL, NULL, NULL, NULL, 89, 0, 0, '0', NULL, NULL, NULL, NULL, 7);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(88, 'Bergen Catholic High School', NULL, NULL, NULL, NULL, 90, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(90, 'Taft School', NULL, NULL, NULL, NULL, 92, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(95, 'Collegiate School', NULL, NULL, NULL, NULL, 97, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(101, 'Buckingham Browne & Nichols', NULL, NULL, NULL, NULL, 103, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(75, 'Andover High School', NULL, NULL, NULL, NULL, 77, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(102, 'Newman School', NULL, NULL, NULL, NULL, 104, 0, 0, '0', NULL, NULL, NULL, NULL, 7);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(103, 'J P Stevens High School', NULL, NULL, NULL, NULL, 105, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(104, 'Morgantown High School', NULL, NULL, NULL, NULL, 106, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(105, 'Beth Blumberg', NULL, NULL, NULL, NULL, 107, 0, 0, '0', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(106, 'Phillips Academy', NULL, NULL, NULL, NULL, 108, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(108, 'Holderness', NULL, NULL, NULL, NULL, 110, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(111, 'Oblong Island', NULL, NULL, NULL, NULL, 113, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(112, 'Newton North High School', NULL, NULL, NULL, NULL, 114, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(113, 'georgetown day school', NULL, NULL, NULL, NULL, 115, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(89, 'Scarsdale High School', NULL, NULL, NULL, NULL, 91, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(77, 'Lexington High School', NULL, NULL, NULL, NULL, 79, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(117, 'Saint Ann''s', NULL, NULL, NULL, NULL, 119, 0, 0, '0', NULL, NULL, NULL, NULL, 7);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(121, 'Kent School', NULL, NULL, NULL, NULL, 123, 0, 0, '0', NULL, NULL, NULL, NULL, 7);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(99, 'Boston Latin School', NULL, NULL, NULL, NULL, 101, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(124, 'WW-P High School South', NULL, NULL, NULL, NULL, 126, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(47, 'Blair Math Team', NULL, NULL, NULL, NULL, 50, 0, 0, '0', NULL, NULL, NULL, NULL, 7);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(119, 'Boston University Academy', NULL, NULL, NULL, NULL, 121, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(120, 'Greater Hartford Academy of Mathematics & Science', NULL, NULL, NULL, NULL, 122, 0, 0, '0', NULL, NULL, NULL, NULL, 7);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(125, 'South Kent School', NULL, NULL, NULL, NULL, 127, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(126, 'Fairfax Math Circle', NULL, NULL, NULL, NULL, 128, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(127, 'Bergen County Academies', NULL, NULL, NULL, NULL, 129, 0, 0, '0', NULL, NULL, NULL, NULL, 7);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(67, 'Hollis Brookline High School', NULL, NULL, NULL, NULL, 69, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(64, 'Bishop Stang High School', NULL, NULL, NULL, NULL, 66, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(132, 'Newton South High School', NULL, NULL, NULL, NULL, 134, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(133, 'the Lawrenceville School', NULL, NULL, NULL, NULL, 135, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(135, 'Choate Rosemary Hall', NULL, NULL, NULL, NULL, 137, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(136, 'MN All-State Math Team', NULL, NULL, NULL, NULL, 138, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(137, 'Westford Academy', NULL, NULL, NULL, NULL, 139, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(97, 'Northfield Mount Hermon School', NULL, NULL, NULL, NULL, 99, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(138, 'Framingham High School', NULL, NULL, NULL, NULL, 140, 0, 0, '0', NULL, NULL, NULL, NULL, 7);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(139, 'Wayzata High School', NULL, NULL, NULL, NULL, 141, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(141, 'Bayside High School', NULL, NULL, NULL, NULL, 143, 0, 0, '0', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(142, 'Boston Global Education Inc.', NULL, NULL, NULL, NULL, 144, 0, 0, '0', NULL, NULL, NULL, NULL, 7);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(147, 'Edina High School', NULL, NULL, NULL, NULL, 149, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(150, 'New Hampton School', NULL, NULL, NULL, NULL, 152, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(151, 'Belmont High School', NULL, NULL, NULL, NULL, 153, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(153, 'Groton School', NULL, NULL, NULL, NULL, 155, 0, 0, '0', NULL, NULL, NULL, NULL, 7);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(156, 'Poolesville Magnet Math', NULL, NULL, NULL, NULL, 158, 0, 0, '0', NULL, NULL, NULL, NULL, 7);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(128, 'Winston Churchill High School', NULL, NULL, NULL, NULL, 130, 0, 0, '0', NULL, NULL, NULL, NULL, 2);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(201, 'The Sage School', NULL, NULL, NULL, NULL, 203, 0, 0, '0', NULL, NULL, NULL, NULL, 7);
INSERT INTO `organizations` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`, `school_type`, `division`) VALUES(148, 'St. Paul Preparatory School', NULL, NULL, NULL, NULL, 150, 0, 0, '0', NULL, NULL, NULL, NULL, 1);
