SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


CREATE TABLE IF NOT EXISTS schools (
  id int(11) NOT NULL AUTO_INCREMENT,
  `name` text,
  email text,
  address text,
  paid tinyint(1) DEFAULT NULL,
  `comment` text,
  accountID int(11) DEFAULT NULL,
  reg_teams int(11) DEFAULT '0',
  reg_students int(11) DEFAULT '0',
  payment varchar(10) NOT NULL DEFAULT '0',
  canceled tinyint(1) DEFAULT NULL,
  paid2 tinyint(1) DEFAULT NULL,
  proctors text,
  school_type varchar(200) DEFAULT NULL,
  division int(11) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(260, 'Ward Melville High School', NULL, '380 Old Town Road\nEast Setauket, NY 11733-3499', 1, NULL, 272, 2, 12, '120', NULL, NULL, '', 'public_small', 2);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(262, 'Vestal High School', NULL, '205 Woodlawn Drive\nVestal, NY 13850', 1, NULL, 274, 1, 5, '50', NULL, NULL, '', 'public_small', 2);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(263, 'Thomas S Wootton High School', NULL, '2100 Wootton Parkway\nRockville, MD 20850', 1, NULL, 275, 1, 8, '80', NULL, NULL, '', 'public_big', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(265, 'Lawrence Woodmere Academy', NULL, '336 Woodmere Boulevard\nWoodmere, NY 11598-2068', 1, NULL, 277, 1, 5, '50', NULL, NULL, '', 'private', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(266, 'Glenforest Secondary School', NULL, '3575 Fieldgate Drive, Mississauga, Ontario, Canada', 1, NULL, 278, 1, 1, '10', NULL, NULL, '', 'regional', 3);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(267, 'Bayside High School', NULL, '3224 Corporal Kennedy Street , Bayside, NY 11361-1061', 1, NULL, 279, 1, 1, '10', NULL, NULL, '', 'individual', 3);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(270, 'Lexington High School', NULL, '251 Waltham Street\nLexington MA, 02421', 1, NULL, 282, 3, 24, '240', NULL, NULL, '', 'public_small', 2);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(271, 'Lehigh Valley', NULL, 'Several high schools in our area', 1, NULL, 283, 1, 8, '80', NULL, NULL, '', 'regional', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(272, 'All Penn', NULL, 'Multiple schools in our region', 1, NULL, 284, 1, 8, '80', NULL, NULL, '', 'regional', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(273, 'Eastern PA', NULL, 'Multiple regional schools', 1, NULL, 285, 1, 3, '70', NULL, NULL, '', 'regional', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(274, 'Cordova High School', NULL, '1800 Berryhill Road\nCordova, TN  38016', 1, NULL, 286, 2, 14, '140', NULL, NULL, '', 'public_big', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(277, 'Pittsford Sutherland High School', NULL, '55 Sutherland Street\nPittsford, NY 14534-1978', 1, NULL, 289, 1, 1, '10', NULL, NULL, '', 'individual', 3);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(278, 'Thomas R. Grover Middle School', NULL, '10 Southfield Rd. Princeton Junction, NJ  ', 1, NULL, 290, 1, 6, '0', NULL, NULL, '', 'public_small', 2);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(281, 'Portsmouth Abbey School', NULL, '285 Cory''s Lane, Portsmouth, RI', 1, NULL, 293, 1, 8, '80', NULL, NULL, '', 'private', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(282, 'Worcester Academy', NULL, '81 Providence Street\nWorcester, MA  01604', 1, NULL, 294, 3, 24, '240', NULL, NULL, '', 'private', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(283, 'The Roxbury Latin School', NULL, '101 St. Theresa Ave.\nWest Roxbury, MA 02132', 0, NULL, 295, 1, 8, '0', NULL, NULL, '', 'private', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(284, 'Kent School', NULL, '1 Macedonia Road\nKent CT\n06757', 1, NULL, 296, 1, 8, '80', NULL, NULL, '', 'private', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(285, 'Michigan All-Stars', NULL, '22305 W. 13 Mile Rd\nBeverly Hills, MI  48025', 1, 'pay 80 day of', 297, 1, 8, '80', NULL, NULL, '', 'private', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(286, 'Albany Area Math Circle', NULL, '73 Hiawatha Dr.\nGuilderland NY 12084', 1, NULL, 298, 3, 24, '240', NULL, NULL, '', 'regional', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(287, 'Phillips Exeter Academy', NULL, '20 Main Street', 1, NULL, 299, 3, 24, '240', NULL, NULL, '', 'private', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(288, 'Shanghai', NULL, 'Shanghai\nChina', 1, NULL, 300, 3, 22, '220', NULL, NULL, '', 'public_big', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(289, 'Idea Math ', NULL, 'Lexington, MA', 1, NULL, 301, 1, 8, '80', NULL, NULL, '', 'individual', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(290, 'Morgantown High School', NULL, '109 Wilson Avenue\nMorgantown, WV 26501', 1, NULL, 302, 1, 8, '120', NULL, NULL, '', 'public_small', 2);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(294, 'Lincoln-Sudbury Regional High School', NULL, '90 Lincoln Road, Sudbury, MA 01776', 1, NULL, 306, 2, 12, '120', NULL, NULL, '', 'public_small', 2);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(293, 'Wilbraham & Monson Academy', NULL, '423 Main Street\nWilbraham MA 01095', 1, NULL, 305, 2, 14, '140', NULL, NULL, '', 'private', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(295, 'Shaker High School', NULL, '445 Watervliet-\nShaker Rd. \nLatham, NY 12110', 0, 'emailed about rooms', 307, 2, 11, '0', NULL, NULL, '', 'public_small', 2);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(307, ' Academy of Notre Dame', NULL, '180 Middlesex Road,  Tyngsboro, MA 01879', 0, 'pay 15 day of', 321, 1, 1, '0', NULL, NULL, '', 'private', 3);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(310, 'The Lawrenceville School', NULL, '2500 Main Street\nLawrenceville, NJ 08648', 1, NULL, 324, 2, 16, '160', NULL, NULL, '', 'private', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(311, 'Union County Magnet High School', NULL, '1776 Raritan Road\nScotch Plains, NJ 07076', 0, NULL, 325, 1, 1, '0', NULL, NULL, '', 'magnet', 3);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(315, 'Toronto', NULL, 'No address', 1, NULL, 329, 2, 16, '160', NULL, NULL, '', 'individual', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(468, 'Greater Hartfiord Academy of Math & Science', NULL, '15 Vernon St.\nHartford, CT 06106', 0, NULL, 491, 0, 0, '0', NULL, NULL, '', 'magnet', NULL);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(316, 'Deerfield Academy', NULL, '7 Boyden Lane\nDeerfield, MA 01342', 1, 'think theyve paid', 330, 1, 8, '80', NULL, NULL, '', 'private', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(317, 'First Presbyterian Day School', NULL, '5671 Calvin Drive\nMacon, GA 31210', 1, NULL, 331, 1, 8, '80', NULL, NULL, '', 'private', 2);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(318, 'TJHSST', NULL, '6560 Braddock Rd.\nAlexandria, VA 22312', 1, NULL, 332, 3, 24, '240', NULL, NULL, '', 'magnet', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(319, 'HCSSiM', NULL, '92 Branchwood Lane,\nNanuet, NY 10954', 1, NULL, 333, 1, 8, '80', NULL, NULL, '', 'individual', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(329, 'ABRHS', NULL, '36 Charter Road, Acton, MA 01720 ', 1, NULL, 343, 1, 8, '80', NULL, NULL, '', 'public_small', 2);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(321, 'Hunter College High School', NULL, '71 East 94th Street\nNew York, NY\n10128', 0, NULL, 335, 1, 8, '0', NULL, NULL, '', 'special', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(322, 'Individual', NULL, '3641 Goldridge Rd, Eau Claire, WI 54701', 1, NULL, 336, 1, 1, '10', NULL, NULL, '', 'individual', 3);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(330, 'Newton South High School', NULL, '140 Brandeis Rd.\nNewton MA, 02459', 1, NULL, 344, 3, 24, '240', NULL, NULL, '', 'public_big', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(331, 'Olympiads School', NULL, '102-200 Consumers Rd.\nNorth York, Ontario \nCanada   M2J 4R4', 1, NULL, 345, 3, 24, '240', NULL, NULL, '', 'private', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(333, 'Weston Collegiate Institute', NULL, '100 Pine Street\nToronto, Ontario\nM9N 2Y9', 1, NULL, 347, 2, 11, '110', NULL, NULL, '', 'public_small', 2);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(335, 'Collegiate School', NULL, '260 W 78th St.\nNew York, NY 10024 ', 1, NULL, 349, 2, 13, '160', NULL, NULL, '', 'private', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(336, 'Oakmont Regional High', NULL, '9Oakmont Drive \nAshburnham, MA 01430', 1, NULL, 350, 1, 5, '0', NULL, NULL, '', 'regional', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(337, 'Nashoba Regional High School', NULL, '12 Green Road\nBolton, MA  01740', 1, NULL, 351, 3, 24, '240', NULL, NULL, '', 'public_small', 2);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(338, 'Northfield Mount Hermon School', NULL, 'One Lamplighter Way\nMount Hermon, MA 01354', 1, NULL, 352, 2, 14, '325', NULL, NULL, '', 'private', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(339, 'Boston Latin School', NULL, '78 Ave Louis Pasteur\nBoston MA 02115', 1, NULL, 353, 1, 8, '105', NULL, NULL, '', 'public_small', 2);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(340, 'Chesapeake', NULL, '10420 Blue Arrow Court\nColumbia, MD 21044', 1, NULL, 354, 1, 8, '80', NULL, NULL, '', 'regional', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(341, 'Evil Geniuses For A Better Tomorrow', NULL, '6 Garfield Drive\nWestborough MA, 01581\n', 1, NULL, 355, 1, 8, '80', NULL, NULL, '', 'regional', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(343, 'Montgomery Blair High School', NULL, '51 University Blvd East\nSilver Spring, MD 20901-2451', 1, NULL, 357, 1, 8, '80', NULL, NULL, '', 'individual', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(344, 'Western Massachusetts ARML', NULL, 'c/o Richard Yanco\nWorcester Academy\n81 Providence Street\nWorcester, MA  01604', 1, NULL, 358, 2, 12, '120', NULL, NULL, '', 'regional', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(345, 'Fairfax Math Circle', NULL, '5303 Esabella Court\nFairfax, VA 22032', 1, NULL, 359, 2, 14, '200', NULL, NULL, '', 'regional', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(346, 'Westford Academy', NULL, '30 Patten Road\nWestford, MA 01886', 1, NULL, 360, 2, 16, '160', NULL, NULL, '', 'public_small', 2);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(348, 'A.Y. Jackson Secondary School', NULL, '50 Francine Drive\nNorth York, Ontario, Canada\nM2H 2G6', 1, NULL, 362, 1, 1, '10', NULL, NULL, '', 'private', 3);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(391, 'Florida', NULL, 'Florida', 1, NULL, 407, 2, 16, '160', NULL, NULL, '', 'regional', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(392, 'Commack High School', NULL, '1 Scholar Lane\nCommack, New York 11725-1526', 1, NULL, 408, 1, 8, '80', NULL, NULL, '', 'public_big', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(353, 'Jericho High School', NULL, '99 cedar swamp road Jericho NY 11753', 1, NULL, 367, 1, 6, '80', NULL, NULL, '', 'individual', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(354, 'GHAMAS', NULL, '15 Vernon Street\nHartford, Connecticut 06106', 1, NULL, 368, 1, 6, '60', NULL, NULL, '', 'magnet', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(355, 'Phillips Academy', NULL, '180 Main St.\nAndover, MA  01810', 1, NULL, 369, 2, 16, '240', NULL, NULL, '', 'private', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(356, 'Paul VI Catholic High School', NULL, '10675 Fairfax Boulevard Fairfax, VA 22030', 1, NULL, 370, 1, 1, '15', NULL, NULL, '', 'private', 3);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(357, 'New Jersey Schools', NULL, '165 Whippany Road\nWhippany NJ 07981', 0, 'pay 60 day of', 373, 1, 4, '0', NULL, NULL, '', 'regional', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(358, 'North Quincy High School', NULL, '316 Hancock St.\nQuincy, MA 02171', 1, NULL, 374, 2, 9, '90', NULL, NULL, '', 'public_small', 2);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(450, 'AAST', NULL, '200 Hackensack Avenue\nHackensack, NJ 07601', 1, NULL, 472, 3, 24, '240', NULL, NULL, '', 'magnet', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(451, 'Somerset High School Parent', NULL, '520 Kenneth Ave.\nSomerset, MA  02725', 0, NULL, 473, 0, 0, '0', NULL, NULL, '', 'individual', NULL);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(361, 'West Windsor-Plainsboro HS North', NULL, '90 Grovers Mill Road\nPlainsboro, NJ 08536', 1, NULL, 377, 2, 16, '160', NULL, NULL, '', 'public_small', 2);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(362, 'Chelmsford High School', NULL, '200 Richardson Rd\nChelmsford, MA 01863 ', 1, NULL, 378, 2, 16, '160', NULL, NULL, '', 'public_small', 2);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(363, 'Hopkins School', NULL, '986 Forest Rd.\nNew Haven, CT 06515', 1, NULL, 379, 1, 8, '175', NULL, NULL, '', 'private', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(365, 'A. Y. Jackson S. S.', NULL, '50 Francine Drive\nNorth York, Ontario\nM2H 2G6', 0, NULL, 381, 1, 1, '0', NULL, NULL, '', 'individual', 3);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(368, 'The Hotchkiss School', NULL, '11 Interlaken Rd. \nP.O.Box 800\nLakeville, CT 06039', 1, 'pay 160 day of', 384, 2, 16, '160', NULL, NULL, '', 'special', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(371, 'Lake Braddock Secondary School', NULL, '9712 thorn bush drive \nfairfax station, VA 22039\n703-646-4263', 1, NULL, 387, 1, 1, '10', NULL, NULL, '', 'public_small', 3);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(372, 'Malden High School', NULL, '77 salem st,\nMalden, MA 02148', 1, NULL, 388, 1, 6, '60', NULL, NULL, '', 'public_small', 2);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(374, 'Emma Willard School', NULL, '285 Pawling Ave.\nTroy, NY  12180', 1, NULL, 390, 1, 8, '80', NULL, NULL, '', 'private', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(376, 'Individual', NULL, 'Individual', 1, NULL, 392, 1, 1, '10', NULL, NULL, '', 'individual', 3);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(377, 'Winchester High School', NULL, '80 skillings rd,\nwinchester, ma 01890', 1, NULL, 393, 2, 16, '240', NULL, NULL, '', 'public_small', 2);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(378, 'Bishop Brady High School', NULL, '25 Columbus Ave\nConcord, NH 03301', 1, NULL, 394, 2, 16, '160', NULL, NULL, '', 'special', 2);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(379, 'Linden Hall School for Girls', NULL, '212 E.Main St.Lititz,PA.17543', 1, NULL, 395, 1, 1, '10', NULL, NULL, '', 'individual', 3);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(380, 'M.E.K. Review', NULL, '261 1st st\nPalisades Park, NJ 07650', 1, NULL, 396, 1, 5, '75', NULL, NULL, '', 'special', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(382, 'Scarsdale High School', NULL, '1059 Post Road, Scarsdale, NY 10583', 1, NULL, 398, 1, 3, '45', NULL, NULL, '', 'public_small', 2);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(383, 'North Carolina', NULL, '1000 Enderbury Drive\nRaleigh, NC 27614', 0, NULL, 399, 1, 6, '0', NULL, NULL, '', 'regional', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(384, 'The Wheeler School', NULL, '216 Hope St.\nProvidence, RI\n02906', 1, NULL, 400, 1, 8, '120', NULL, NULL, '', 'private', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(393, 'New York City Math Team', NULL, 'Stuyvesant High School\n345 Chambers St.\nNew York, NY 10282', 1, NULL, 409, 3, 24, '320', NULL, NULL, '', 'regional', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(394, 'Newton North High School', NULL, '767 Watertown st.\nnewton, ma\n02465', 0, NULL, 410, 1, 6, '0', NULL, NULL, '', 'public_small', 2);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(395, 'IMSA', NULL, '1500 West Sullivan\nAurora, IL, 60506', 1, NULL, 411, 1, 8, '80', NULL, NULL, '', 'magnet', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(403, 'Maur Hill-Mount Academy', NULL, '1000 Green Street,Atchison,Kansas', 0, NULL, 419, 1, 8, '0', NULL, NULL, '', 'private', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(399, 'Belmont High School', NULL, '221 Concord Avenue\nBelmont MA, 02478', 1, NULL, 415, 2, 11, '110', NULL, NULL, '', 'public_small', 2);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(400, 'Westborough High School', NULL, '90 West Main Street,\nWestborough, MA 01581', 1, NULL, 416, 1, 8, '120', NULL, NULL, '', 'public_small', 2);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(401, 'Buckingham Browne and Nichols', NULL, '80 Gerry''s Landing Road\nCambridge, MA 02138', 1, NULL, 417, 2, 12, '120', NULL, NULL, '', 'private', 1);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(402, 'South Brunswick High School', NULL, '750 Ridge Road\nMonmouth Junction, NJ 08852', 1, 'check in mail', 418, 1, 8, '120', NULL, NULL, '', 'public_small', 2);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(404, 'Andover High School', NULL, '80 Shawsheen Rd.\nAndover MA 01810', 1, NULL, 420, 1, 8, '80', NULL, NULL, '', 'public_small', 2);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(405, 'Danbury High School', NULL, '43 clapboard Ridge Road, Danbury,CT 06811', 0, NULL, 421, 1, 4, '0', NULL, NULL, '', 'public_small', 2);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(406, 'Canandaigua Academy Plus One', NULL, '1 Academy Circle\nCanandaigua, NY 14424', 1, NULL, 422, 3, 22, '220', NULL, NULL, '', 'public_small', 2);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(407, 'Pomperaug High School', NULL, 'Judd Road, Southbury, Ct 06488', 0, NULL, 423, 1, 1, '0', NULL, NULL, '', 'regional', 3);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(410, 'Holmdel High School', NULL, '36 Crawfords Corner Road\nHolmdel, NJ 07733', 1, NULL, 426, 1, 1, '10', NULL, NULL, '', 'individual', 3);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(413, 'West Windsor-Plainsboro High School South', NULL, '346 Clarksville Rd Princeton Jct, NJ 08550', 0, NULL, 429, 0, 0, '0', NULL, NULL, '', 'public_small', NULL);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(469, 'Sabio Academy', NULL, '2628 Patriot Blvd\nGlenview IL 60026', 0, NULL, 492, 0, 0, '0', NULL, NULL, '', 'private', NULL);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(449, 'Taft School', NULL, '110 Woodbury Road, Watertown, CT 06795', 0, NULL, 471, 0, 0, '0', NULL, NULL, '', 'individual', NULL);
INSERT INTO schools (id, name, email, address, paid, comment, accountID, reg_teams, reg_students, payment, canceled, paid2, proctors, school_type, division) VALUES(456, 'Hunter College High School', NULL, '71 East 94th Street ,New York,NY,10128', 0, NULL, 478, 0, 0, '0', NULL, NULL, '', 'individual', NULL);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
