SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


CREATE TABLE IF NOT EXISTS `schools` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` text,
  `email` text,
  `address` text,
  `paid` tinyint(1) DEFAULT NULL,
  `comment` text,
  `accountID` int(11) DEFAULT NULL,
  `reg_teams` int(11) DEFAULT '0',
  `reg_students` int(11) DEFAULT '0',
  `payment` varchar(10) NOT NULL DEFAULT '0',
  `canceled` tinyint(1) DEFAULT NULL,
  `paid2` tinyint(1) DEFAULT NULL,
  `proctors` text,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(144, 'Western Reserve Academy', NULL, '115 College Street, Hudson, Ohio, 44236', 0, NULL, 144, 1, 8, '120', NULL, 1, 'moo\r\ncow\r\n');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(123, 'Phillips Exeter Academy', NULL, '20 Main Street\nNH, 03833', 1, NULL, 123, 3, 24, '240', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(124, 'Monroe County', NULL, '875 Ridge Rd, Webster, NY 14580', 1, NULL, 124, 1, 8, '80', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(125, 'Phillips Academy', NULL, '180 Main St.\nAndover, MA  01810', 1, NULL, 125, 2, 16, '160', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(126, 'Newton South High School', NULL, '140 Brandeis Road\nNewton, MA 02459', 1, NULL, 126, 2, 16, '160', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(127, 'Edith C. Baker school', NULL, 'Brookline, MA 02467', 1, NULL, 127, 1, 1, '10', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(128, 'Taft School', NULL, '110 Woodbury Road\nWatertown, CT  06795', 1, NULL, 128, 1, 8, '80', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(129, 'Lake Forest', NULL, '1500 West Kennedy Road\nLake Forest, IL', 1, NULL, 129, 2, 14, '140', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(132, 'ThaiScholar', NULL, '333 Christian Street Wallingford 06492', 1, NULL, 132, 1, 8, '80', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(136, 'Acton-Boxborough Regional High School', NULL, '16 Charter Road, Acton, MA, 01720', 1, NULL, 136, 1, 6, '60', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(137, 'No Affiliated School', NULL, 'No Affiliated School', 1, NULL, 137, 2, 16, '100', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(138, 'First Presbyterian Day School', NULL, '5671 Calvin Drive\nMacon, GA 31210', 1, NULL, 138, 1, 8, '80', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(140, 'WWP High School South', NULL, '346 Clarksville Road\nPrinceton Jct. NJ 08550', 1, NULL, 140, 1, 8, '80', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(141, 'Somerset High School', NULL, 'Grandview Ave\nSomerset, MA 02726', 1, NULL, 141, 1, 8, '120', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(145, 'Worcester Academy', NULL, '81 Providence Street\nWorcester, MA  01604', 1, NULL, 145, 2, 16, '160', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(146, 'Newtown High School', NULL, '12 Berkshire Road, Newtown, CT, 06482', 0, NULL, 146, 1, 0, '0', NULL, 0, NULL);
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(148, 'Morris Hills', NULL, '520 West Main Street\nRockaway, NJ 07866', 1, NULL, 148, 1, 8, '80', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(149, 'Olympiads School', NULL, '200 Consumers Rd., #102\nNorth York, ON., Canada', 1, NULL, 149, 3, 24, '240', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(150, 'Cambridge Rindge and Latin School', NULL, '459 Broadway\nCambridge MA 02138', 1, NULL, 150, 1, 8, '80', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(151, 'Lexington High School', NULL, '251 Waltham Street, Lexington, MA 02421', 1, NULL, 151, 3, 24, '240', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(153, 'Enka High School', NULL, 'Sadi Gülçelik Spor Tesisi\nİstinye 34460\nİstanbul/TURKEY', 1, NULL, 153, 1, 2, '20', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(222, 'Darrow School', NULL, '110 Darrow Rd\nNew Lebanon, NY 12125', 1, NULL, 222, 1, 6, '60', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(155, 'IDEA math (Math circle)', NULL, 'P.O.Box 338\nExeter\nNH 03833', 1, NULL, 155, 2, 16, '160', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(157, 'Northfield Mount Hermon School', NULL, 'One Lamplighter Way\n#4754\nMount Hermon, MA 01354', 1, NULL, 157, 2, 14, '140', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(242, 'Florida', NULL, 'Florida', 1, NULL, 242, 3, 24, '240', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(243, 'Olympiads High School', NULL, '88 Morrison Cres. Markham, Ontario, Canada L3R 9K9', 0, NULL, 243, 0, 0, '0', NULL, 0, NULL);
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(160, 'TJHSST', NULL, '6560 Braddock Rd.\nAlexandria, VA 22312', 0, NULL, 160, 3, 24, '240', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(163, 'Cordova High School', NULL, '1800 Berryhill Road\nCordova, TN  38016', 1, NULL, 163, 2, 16, '160', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(166, 'WWP High School North', NULL, '90 Grovers Mill Road\nPO Box 50\nPlainsboro NJ 08536', 1, NULL, 166, 2, 16, '160', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(168, 'HCSSiM', NULL, '92 Branchwood Lane,\nNanuet, New York 10954', 1, NULL, 168, 2, 16, '160', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(169, 'Ward Melville', NULL, '4 English Ivy Lane\nLake Grove, NY 11755', 1, NULL, 169, 2, 13, '130', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(170, 'Yang Academy', NULL, '111 Central Avenue\nGaithersburg, MD 20877', 1, NULL, 170, 1, 1, '10', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(171, 'Westford Academy', NULL, '30 Patten Road\nWestford, MA 01886', 1, NULL, 171, 3, 24, '160', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(220, 'Montrose School', NULL, '29 North St. Medfield, MA', 0, NULL, 220, 1, 0, '0', NULL, 0, NULL);
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(174, 'Albany Area Math Circle', NULL, '9 Ethan Allen St.\nFort Edward, NY 12828', 1, NULL, 174, 3, 24, '240', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(175, 'Hun School of Princeton', NULL, '176 Edgerstoune road, Princeton NJ 08540', 1, NULL, 175, 1, 2, '20', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(176, 'AAST', NULL, '200 Hackensack Avenue, Hackensack NJ 07601', 0, NULL, 176, 3, 24, '240', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(177, 'East Brunswick High School', NULL, '380 Cranbury Road\nEast Brunswick, NJ 08816', 1, NULL, 177, 2, 10, '100', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(178, 'Thomas Wootton High School', NULL, '2100 Wootton Parkway Rockville Md 20850', 1, NULL, 178, 1, 8, '80', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(179, 'N/A', NULL, '6 garfield drive\nWestborough MA, 01581\n', 1, NULL, 179, 1, 8, '80', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(180, 'Loomis Chaffee School', NULL, '4 Batchelder Road\nWindsor, CT  06095', 1, NULL, 180, 1, 8, '80', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(181, 'Individuals', NULL, '9703 bridge creek road, north little rock, AR, 72120', 1, NULL, 181, 1, 1, '10', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(182, 'Methacton High School', NULL, '1001 Kriebel Mill Road\nNorristown PA 19403', 1, NULL, 182, 2, 16, '80', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(183, 'The Roxbury Latin School', NULL, '101 Saint Theresa Avenue\nWest Roxbury, MA 02132', 1, NULL, 183, 1, 8, '80', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(186, 'Western MASS ARML Team', NULL, '17 Woodside Drive\nSterling, MA 01564', 1, NULL, 186, 2, 16, '160', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(187, 'The Tatnall School', NULL, '1501 Barley Mill Road\nWilmington DE, 19807', 0, NULL, 187, 1, 1, '0', NULL, 0, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(188, 'Wootlings', NULL, '34 Oak Shadows Court\nCatonsville, MD 21228', 1, NULL, 188, 1, 8, '80', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(190, 'Ridgewood High School', NULL, '627 E. Ridgewood Ave\nRidgewood NJ 07450', 1, NULL, 190, 1, 8, '80', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(192, 'Mass Academy', NULL, '85 Prescott Street\nWorcester, MA\n01605', 1, NULL, 192, 1, 8, '80', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(193, 'Illinois Math and Science Academy', NULL, '1500 West Sullivan Road\nAurora, Il 60506', 1, NULL, 193, 1, 8, '80', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(194, 'Soli Deo Gloria Math Club', NULL, 'PO Box 837, McDonough GA 30253', 1, NULL, 194, 1, 8, '80', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(196, 'Boston University Academy', NULL, 'One University Road\nBoston, MA 02215', 0, NULL, 196, 1, 1, '0', NULL, 0, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(197, 'Andover High School', NULL, '80 Shawsheen Rd.\nAndover, MA 01810', 1, NULL, 197, 1, 8, '80', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(214, 'Long Island', NULL, '100 Rumford Road,\nKings Park, NY 11754', 1, NULL, 214, 1, 8, '80', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(199, 'St. Paul''s School', NULL, '325 Pleasant st.\nConcord, NH', 0, NULL, 199, 1, 8, '0', NULL, 0, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(200, 'NYC Math Team', NULL, '346 Chambers St\nNew York, NY 10282', 1, NULL, 200, 3, 24, '240', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(201, 'math club', NULL, '57-00 223 Street\nBayside, NY 11364', 0, NULL, 201, 1, 3, '35', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(202, 'Laurel School', NULL, 'One Lyman Circle\nShaker Heights, OH 44122-2199', 1, NULL, 202, 1, 1, '10', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(203, 'Detroit Country Day School', NULL, '42063 Ponmeadow Dr, Northville, MI 48168', 1, NULL, 203, 1, 8, '80', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(205, 'Joseph Case High School', NULL, '70 School St.\nSwansea, MA 02777', 1, NULL, 205, 1, 8, '120', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(206, 'St. Joseph High School', NULL, '2320 Huntington Turnpike\nTrumbull, CT 06611', 1, NULL, 206, 1, 1, '10', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(207, 'Emma Willard School', NULL, '285 Pawling Ave., Troy, NY  12180', 1, NULL, 207, 1, 8, '80', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(208, 'Chelmsford High School', NULL, '190 Richardson Road\nN. Chelmsford, MA 01863 ', 1, NULL, 208, 1, 8, '80', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(209, 'Wheeler School', NULL, '216 Hope Street\nProvidence\nRI 02906', 1, NULL, 209, 1, 8, '80', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(210, 'Dover-Sherborn High School', NULL, '9, Junction Street,\nDover, MA 02030', 1, NULL, 210, 1, 2, '20', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(211, 'Belmont and West Lafayette', NULL, '707 Sugar Hill Drive\nWest Lafayette IN, 47906', 1, NULL, 211, 1, 8, '105', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(212, 'Edgemont Junior/Senior High School', NULL, '200 White Oak Lane\nScarsdale NY, 10583', 1, NULL, 212, 1, 3, '30', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(213, 'Deerfield Academy', NULL, '7 Boyden Lane\nDeerfield, MA 01342', 1, NULL, 213, 1, 8, '120', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(215, 'Robinson Secondary School', NULL, '5035 Sideburn Road\nFairfax, Virginia, 22032', 1, NULL, 215, 1, 5, '50', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(216, 'Individuals', NULL, 'individual', 0, NULL, 216, 1, 1, '0', NULL, 0, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(218, 'Whippany Park High School', NULL, '165 Whippany Road \nWhippany New Jersey 07981', 1, NULL, 218, 1, 1, '10', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(223, 'South Brunswick High School', NULL, '750 Ridge Road\nMonmouth Junction, NJ 08852', 1, NULL, 223, 2, 16, '160', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(224, 'Stuyvesant', NULL, 'Jim Cocoros\n345 Chambers Street\nNew York, NY 10282', 1, NULL, 224, 1, 8, '80', NULL, 1, '');
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(245, 'North Quincy High School', NULL, '316 Hancock Street Quincy, MA 02171', 0, NULL, 245, 0, 0, '0', NULL, 0, NULL);
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(226, 'The Lawrenceville School', NULL, '2500 Main Street\nLawrenceville, NJ 08648\n', 0, NULL, 226, 0, 0, '0', NULL, 0, NULL);
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(227, 'Lincoln-Sudbury Regional High School', NULL, '390 Lincoln Road, Sudbury, MA 01776', 0, NULL, 227, 0, 0, '0', NULL, 0, NULL);
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(228, 'Concord Academy', NULL, '166 Main Street\nConcord, MA 01742', 0, NULL, 228, 0, 0, '0', NULL, 0, NULL);
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(229, 'Wilbraham & Monson Academy', NULL, '423 Main Street, Wilbraham MA 01095', 0, NULL, 229, 0, 0, '0', NULL, 0, NULL);
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(233, 'PORTSMOUTH ABBEY', NULL, '285 cory''s lane, portsmouth, RI', 0, NULL, 233, 0, 0, '0', NULL, 0, NULL);
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(244, 'JERICHO SENIOR HIGH SCHOOL', NULL, '99 cedar swamp road', 0, NULL, 244, 0, 0, '0', NULL, 0, NULL);
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(246, 'Hunter College High School', NULL, '71 East 94th Street\nNew York, N.Y.\n10128', 0, NULL, 246, 0, 0, '0', NULL, 0, NULL);
INSERT INTO `schools` (`id`, `name`, `email`, `address`, `paid`, `comment`, `accountID`, `reg_teams`, `reg_students`, `payment`, `canceled`, `paid2`, `proctors`) VALUES(251, 'moo', NULL, 'moo', 0, NULL, 263, 0, 0, '0', NULL, NULL, '');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
